<?php

/**
 * CED Portal Installation Script
 * Adapted from FluxBB
 */

define('CED_ROOT', './');

error_reporting(E_ALL);
ini_set('display_errors', 1);

$errors = array();
$success = false;

// Handle installation
if (isset($_POST['install']))
{
    $db_host = trim($_POST['db_host']);
    $db_name = trim($_POST['db_name']);
    $db_username = trim($_POST['db_username']);
    $db_password = $_POST['db_password'];
    $db_prefix = trim($_POST['db_prefix']);
    $base_url = trim($_POST['base_url']);
    $admin_username = trim($_POST['admin_username']);
    $admin_password = $_POST['admin_password'];
    $admin_email = trim($_POST['admin_email']);
    
    // Validate
    if (empty($db_host)) $errors[] = 'Database host is required';
    if (empty($db_name)) $errors[] = 'Database name is required';
    if (empty($db_username)) $errors[] = 'Database username is required';
    if (empty($base_url)) $errors[] = 'Base URL is required';
    if (empty($admin_username)) $errors[] = 'Admin username is required';
    if (empty($admin_password)) $errors[] = 'Admin password is required';
    if (empty($admin_email)) $errors[] = 'Admin email is required';
    
    if (empty($errors))
    {
        // Test database connection
        $link = @mysqli_connect($db_host, $db_username, $db_password);
        if (!$link)
        {
            $errors[] = 'Unable to connect to MySQL server. MySQL reported: '.mysqli_connect_error();
        }
        else
        {
            // Select database
            if (!@mysqli_select_db($link, $db_name))
            {
                $errors[] = 'Unable to select database. MySQL reported: '.mysqli_error($link);
            }
            else
            {
                // Read schema file
                $schema = file_get_contents(CED_ROOT.'schema_fluxbb.sql');
                
                // Execute schema
                $queries = explode(';', $schema);
                foreach ($queries as $query)
                {
                    $query = trim($query);
                    if (!empty($query))
                    {
                        if (!@mysqli_query($link, $query))
                        {
                            $errors[] = 'Database setup failed: '.mysqli_error($link);
                            break;
                        }
                    }
                }
                
                if (empty($errors))
                {
                    // Update admin user
                    $password_hash = password_hash($admin_password, PASSWORD_DEFAULT);
                    $query = "UPDATE {$db_prefix}users SET username='".mysqli_real_escape_string($link, $admin_username)."', password='".mysqli_real_escape_string($link, $password_hash)."', email='".mysqli_real_escape_string($link, $admin_email)."' WHERE id=1";
                    
                    if (!@mysqli_query($link, $query))
                    {
                        $errors[] = 'Failed to create admin user: '.mysqli_error($link);
                    }
                }
                
                if (empty($errors))
                {
                    // Create config file
                    $config = "<?php\n\n";
                    $config .= "/**\n * CED Portal Configuration File\n * Generated by installer\n */\n\n";
                    $config .= "// Database configuration\n";
                    $config .= "\$db_type = 'mysqli';\n";
                    $config .= "\$db_host = '".addslashes($db_host)."';\n";
                    $config .= "\$db_name = '".addslashes($db_name)."';\n";
                    $config .= "\$db_username = '".addslashes($db_username)."';\n";
                    $config .= "\$db_password = '".addslashes($db_password)."';\n";
                    $config .= "\$db_prefix = '".addslashes($db_prefix)."';\n";
                    $config .= "\$p_connect = false;\n\n";
                    $config .= "// Cookie configuration\n";
                    $config .= "\$cookie_name = 'ced_cookie';\n";
                    $config .= "\$cookie_domain = '';\n";
                    $config .= "\$cookie_path = '/';\n";
                    $config .= "\$cookie_secure = 0;\n";
                    $config .= "\$cookie_seed = '".bin2hex(random_bytes(16))."';\n\n";
                    $config .= "// Site URL\n";
                    $config .= "define('CED_BASE_URL', '".addslashes($base_url)."');\n\n";
                    $config .= "// Installation complete flag\n";
                    $config .= "define('CED', 1);\n\n";
                    
                    if (@file_put_contents(CED_ROOT.'include/config.php', $config))
                    {
                        $success = true;
                    }
                    else
                    {
                        $errors[] = 'Unable to write config file. Please make sure the include/ directory is writable.';
                    }
                }
            }
            
            mysqli_close($link);
        }
    }
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CED Portal Installation</title>
    <style>
        body { font: 14px/1.6 Arial, sans-serif; background: #f5f5f5; padding: 20px; }
        .container { max-width: 600px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        h1 { color: #333; margin: 0 0 20px; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; }
        input[type="text"], input[type="password"], input[type="email"] { width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 3px; box-sizing: border-box; }
        button { background: #0066cc; color: #fff; padding: 10px 20px; border: none; border-radius: 3px; cursor: pointer; font-size: 14px; }
        button:hover { background: #0052a3; }
        .error { background: #fee; border: 1px solid #fcc; color: #c00; padding: 10px; border-radius: 3px; margin-bottom: 15px; }
        .success { background: #efe; border: 1px solid #cfc; color: #060; padding: 10px; border-radius: 3px; margin-bottom: 15px; }
        .note { background: #ffc; border: 1px solid #ff9; padding: 10px; border-radius: 3px; margin-bottom: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>CED Portal Installation</h1>
        
        <?php if ($success): ?>
        <div class="success">
            <strong>Installation successful!</strong><br>
            CED Portal has been installed successfully.<br><br>
            <strong>Important:</strong> Please delete the install.php file for security.<br><br>
            <a href="index.php">Go to CED Portal</a>
        </div>
        <?php else: ?>
        
        <?php if (!empty($errors)): ?>
        <div class="error">
            <strong>Installation failed:</strong><br>
            <ul>
                <?php foreach ($errors as $error): ?>
                <li><?php echo htmlspecialchars($error) ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
        
        <div class="note">
            <strong>Before you begin:</strong><br>
            - Make sure you have created a MySQL database<br>
            - Make sure the include/ and cache/ directories are writable<br>
            - Have your database credentials ready
        </div>
        
        <form method="post">
            <h2>Database Settings</h2>
            
            <div class="form-group">
                <label>Database Host:</label>
                <input type="text" name="db_host" value="<?php echo isset($_POST['db_host']) ? htmlspecialchars($_POST['db_host']) : 'localhost' ?>" required>
            </div>
            
            <div class="form-group">
                <label>Database Name:</label>
                <input type="text" name="db_name" value="<?php echo isset($_POST['db_name']) ? htmlspecialchars($_POST['db_name']) : 'ced_portal' ?>" required>
            </div>
            
            <div class="form-group">
                <label>Database Username:</label>
                <input type="text" name="db_username" value="<?php echo isset($_POST['db_username']) ? htmlspecialchars($_POST['db_username']) : 'root' ?>" required>
            </div>
            
            <div class="form-group">
                <label>Database Password:</label>
                <input type="password" name="db_password" value="<?php echo isset($_POST['db_password']) ? htmlspecialchars($_POST['db_password']) : '' ?>">
            </div>
            
            <div class="form-group">
                <label>Table Prefix:</label>
                <input type="text" name="db_prefix" value="<?php echo isset($_POST['db_prefix']) ? htmlspecialchars($_POST['db_prefix']) : 'ced_' ?>" required>
            </div>
            
            <h2>Site Settings</h2>
            
            <div class="form-group">
                <label>Base URL (no trailing slash):</label>
                <input type="text" name="base_url" value="<?php echo isset($_POST['base_url']) ? htmlspecialchars($_POST['base_url']) : 'http://localhost/CED-Portal' ?>" required>
            </div>
            
            <h2>Administrator Account</h2>
            
            <div class="form-group">
                <label>Admin Username:</label>
                <input type="text" name="admin_username" value="<?php echo isset($_POST['admin_username']) ? htmlspecialchars($_POST['admin_username']) : 'admin' ?>" required>
            </div>
            
            <div class="form-group">
                <label>Admin Password:</label>
                <input type="password" name="admin_password" required>
            </div>
            
            <div class="form-group">
                <label>Admin Email:</label>
                <input type="email" name="admin_email" value="<?php echo isset($_POST['admin_email']) ? htmlspecialchars($_POST['admin_email']) : 'admin@example.com' ?>" required>
            </div>
            
            <button type="submit" name="install">Install CED Portal</button>
        </form>
        
        <?php endif; ?>
    </div>
</body>
</html>

